// var x  = 30;
// 	y  = 70;
// 	z1 = 0 ;
// 	z2 = 0 ;
// 	z3 = 0 ;
// 	z4 = 0 ;
// console.log(z1=x+y);
// console.log(z2=x-y);
// console.log(z3=x*y);
// console.log(z4=x/y);
// console.log(z1 < z2);
// console.log(z3 == z4);
